name: Call RSS Reader

on:
  push:
    branches:
      - main
  schedule: 
    - cron: '0 22 * * 1'

jobs:
  check-blackpink-feed:
    uses: jiyeonmolloy/rss-reader/.github/workflows/rss_reader.yml@main
    with:
      rss_url: 'https://www.reddit.com/r/BlackPink.rss'
      keyword: "BlackPink News"
    secrets:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  check-ji-blog-feed:
    uses: jiyeonmolloy/rss-reader/.github/workflows/rss_reader.yml@main
    with:
      rss_url: 'https://jiyeonmolloy.github.io/index.xml'
      keyword: "Ji's Blog Posts"
    secrets:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  check-xcode-release:
    uses: jiyeonmolloy/rss-reader/.github/workflows/rss_reader.yml@main
    with:
      rss_url: 'https://xcodereleases.com/api/all.rss'
      keyword: "Xcode Releases"
    secrets:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}